DICE_STICKERS = {
    1: "CAACAgIAAxkBAAEHpaxmujVCkq8ra-cVERUrqzV2G-FxCQACBnMAAp7OCwABeRelZgnyaW41BA",
    2: "CAACAgIAAxkBAAEHpa5mujVQbotcAbwlXScxKsNrNhkFvwACB3MAAp7OCwABHTuSAdZlD041BA",
    3: "CAACAgIAAxkBAAEHpbBmujVWTlUL391j9vzZq6zYasy-gAACCHMAAp7OCwABK3IbM1dVAtY1BA",
    4: "CAACAgIAAxkBAAEHpbBmujVWTlUL391j9vzZq6zYasy-gAACCHMAAp7OCwABK3IbM1dVAtY1BA",
    5: "CAACAgIAAxkBAAEHpbRmujVjSfuf83OXgAw0SZWusnqCFQACCnMAAp7OCwABB1FnIcyJWCI1BA",
    6: "CAACAgIAAxkBAAEHpbZmujVrlbn-KmZOrDVnoprXDZnC-AACC3MAAp7OCwAB_nCt2sUm8FI1BA"
}
